name = "redirect"
main = "worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat_v2"]
workers_dev = true
routes = [

  { pattern = "balckwolf.dpdns.org", custom_domain = true },
  { pattern = "df.game.naver.com.balckwolf.dpdns.org", custom_domain = true },
  { pattern = "ava.game.naver.com.balckwolf.dpdns.org", custom_domain = true },
  ]
  
  
  [unsafe.metadata.observability]
   enabled = true

[observability.logs]
enabled = true

